const SUPABASE_URL='https://agkdhtocgjenrqfulrft.supabase.co';
const SUPABASE_KEY='sb_publishable_pfy8HFRFHgS6W0qSuiKTFQ_B9Bd5LwH';
const LS_KEY='mahalu_leads_session_v1';
let authListeners=[];
function getStoredSession(){try{return JSON.parse(localStorage.getItem(LS_KEY)||'null')}catch{return null}}
function setStoredSession(s){if(s)localStorage.setItem(LS_KEY,JSON.stringify(s));else localStorage.removeItem(LS_KEY);authListeners.forEach(fn=>fn(s?'SIGNED_IN':'SIGNED_OUT',s))}
function authHeaders(){const s=getStoredSession();return {'apikey':SUPABASE_KEY,'Authorization':`Bearer ${s?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json'}}
function enc(v){return encodeURIComponent(String(v))}
class RestQuery{
  constructor(table){this.table=table;this.method='GET';this.filters=[];this.orderBy=null;this.payload=null;this.returning=false;this.oneMode=null;this.upsertConflict=null}
  select(){this.returning=true;return this} order(col,opt={}){this.orderBy=`${col}.${opt.ascending===false?'desc':'asc'}`;return this} eq(col,val){this.filters.push(`${enc(col)}=eq.${enc(val)}`);return this} maybeSingle(){this.oneMode='maybe';return this} single(){this.oneMode='single';return this} insert(payload){this.method='POST';this.payload=payload;return this} update(payload){this.method='PATCH';this.payload=payload;return this} upsert(payload,opt={}){this.method='POST';this.payload=payload;this.upsertConflict=opt.onConflict||null;return this}
  async execute(){let qs=[];if(this.method==='GET'||this.returning)qs.push('select=*');qs.push(...this.filters);if(this.orderBy)qs.push(`order=${enc(this.orderBy)}`);if(this.upsertConflict)qs.push(`on_conflict=${enc(this.upsertConflict)}`);const url=`${SUPABASE_URL}/rest/v1/${this.table}${qs.length?'?'+qs.join('&'):''}`;const headers=authHeaders();if(this.method!=='GET')headers['Prefer']=this.returning?'return=representation':'return=minimal';if(this.upsertConflict)headers['Prefer']=(this.returning?'return=representation,':'')+'resolution=merge-duplicates';try{const res=await fetch(url,{method:this.method,headers,body:this.method==='GET'?undefined:JSON.stringify(this.payload)});let data=null;const txt=await res.text();if(txt){try{data=JSON.parse(txt)}catch{data=txt}}if(!res.ok)return{data:null,error:{message:data?.message||data?.error_description||`HTTP ${res.status}`}};if(this.oneMode){const arr=Array.isArray(data)?data:(data?[data]:[]);if(this.oneMode==='single'&&arr.length!==1)return{data:null,error:{message:'Data tidak ditemukan atau duplikat.'}};data=arr[0]||null}return{data,error:null}}catch(e){return{data:null,error:{message:'Koneksi ke server gagal. Coba refresh halaman.'}}}}
  then(resolve,reject){return this.execute().then(resolve,reject)}
}
const db={from:t=>new RestQuery(t),auth:{async getSession(){const s=getStoredSession();if(!s)return{data:{session:null}};try{const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders()});if(!r.ok){setStoredSession(null);return{data:{session:null}}}s.user=await r.json();localStorage.setItem(LS_KEY,JSON.stringify(s));return{data:{session:s}}}catch{return{data:{session:s}}}},onAuthStateChange(cb){authListeners.push(cb);return{data:{subscription:{unsubscribe(){authListeners=authListeners.filter(x=>x!==cb)}}}}},async signInWithPassword({email,password}){try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return{data:null,error:{message:d.error_description||d.msg||'Email atau password salah.'}};const s={access_token:d.access_token,refresh_token:d.refresh_token,expires_in:d.expires_in,user:d.user};setStoredSession(s);return{data:{session:s,user:d.user},error:null}}catch{return{data:null,error:{message:'Tidak bisa terhubung ke server. Coba lagi.'}}}},async signOut(){setStoredSession(null);return{error:null}}}};
